# Generated by Django 5.1.6 on 2025-02-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите наименование продукта', max_length=100, verbose_name='Наименование продукта')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите цену продукта', max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(help_text='Укажите описание продукта', verbose_name='Описание продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
